spring:
  application:
    name: alert-service

server:
  port: 8081

feign:
  client:
    cost-api:
      url: http://localhost:8080

slack:
  webhook-url:
  channel: "#finops-alerts"
  username: "FinOps Bot"
  icon-emoji: ":moneybag:"

alert:
  threshold:
    daily-increase-percent: 20
    monthly-budget: 10000
  schedule:
    check-cron: "0 0 * * * *"
    report-cron: "0 0 10 * * *"

logging:
  level:
    com.finops: DEBUG
